# vi: set ft=ruby :
VAGRANTFILE_API_VERSION = '2'
Vagrant.require_version '>= 1.8.2'

CURRENT_DIR = File.expand_path(File.dirname(__FILE__))
DIRNAME     = File.basename(CURRENT_DIR)

#host  = RbConfig::CONFIG['host_os']
hosts = {
    #10.10.10.1 is configured as bridged between the host and 10.10.1.x guests
    "#{DIRNAME}.example.com"  => "10.10.10.10",
}

$admin_preconditions = <<SCRIPT
apt-get update
DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends -y tmux htop vim-nox git-core mercurial subversion wget curl python-software-properties python-pip build-essential g++ default-jdk ruby nodejs golang php5-cli sqlite3
[ -f /tmp/gotty_linux_amd64.tar.gz ] || wget --progress=bar:force https://github.com/yudai/gotty/releases/download/v0.0.13/gotty_linux_amd64.tar.gz -O /tmp/gotty_linux_amd64.tar.gz
[ -f /usr/bin/gotty ] || tar zxf /tmp/gotty_linux_amd64.tar.gz -C /usr/bin/
SCRIPT

$user_preconditions = <<SCRIPT
mkdir -p ~/q1.dir/{or/ga/ni/za/tion,li/nu/x}
touch ~/q1.dir/{{1,2,3,4,5}.pyc,or/{1,2,3}.pyc,or/ga/{1,2,3,4,5,6,7,8,9}.pyc,or/ga/ni/{1,2,3,4,5,6,7,8,9,0}.pyc,or/ga/ni/za/tion/{1,2,3,4,5,6,7}.pyc,li/{1,2,3}.pyc,li/nu/x/{1,2,3,4,5}.pyc}
> ~/q3.in
for i in $(seq 100); do echo "there is $i linux system(s) running ..., wops, error, there is 0 linux system(s) running ...)" >> ~/q3.in; done
wget --progress=bar:force http://veekun.com/static/pokedex/downloads/veekun-pokedex.sqlite.gz
gunzip veekun-pokedex.sqlite.gz && mv veekun-pokedex.sqlite q8.in
SCRIPT

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    hosts.each do |name, ip|
        config.vm.define name do |machine|
            machine.vm.box = "ubuntu/trusty64"
            machine.vm.hostname = name
            machine.vm.network :private_network, ip: ip

            #machine.vm.network "forwarded_port", guest: 80, host: 8080, auto_correct: true, id:"httpd"

            machine.vm.provider "virtualbox" do |vbox|
                vbox.name = name
                vbox.linked_clone = true if Vagrant::VERSION =~ /^1.8/
                vbox.customize ["modifyvm", :id, "--memory", 512]
                vbox.customize ["modifyvm", :id, "--cpuexecutioncap", "50"]
            end

            #$ vagrant plugin install vagrant-hosts
            if Vagrant.has_plugin?('vagrant-hosts')
                machine.vm.provision :hosts, sync_hosts: true
            elsif Vagrant.has_plugin?('vagrant-hostmanager')
                machine.hostmanager.enabled     = true
                machine.hostmanager.manage_host = true
                machine.hostmanager.aliases     = aliases
            end

            #echo cmds, lambda syntax: http://stackoverflow.com/questions/8476627/what-do-you-call-the-operator-in-ruby
            CMD_SCRIPT_ROOT        = -> (cmd) { machine.vm.provision 'shell', path:   cmd, name: cmd, privileged: true  }
            CMD_SCRIPT             = -> (cmd) { machine.vm.provision 'shell', path:   cmd, name: cmd, privileged: false }
            CMD_INLINE_ROOT        = -> (cmd) { machine.vm.provision 'shell', inline: cmd, name: cmd, privileged: true  }
            CMD_INLINE             = -> (cmd) { machine.vm.provision 'shell', inline: cmd, name: cmd, privileged: false }
            CMD_SCRIPT_ALWAYS_ROOT = -> (cmd) { machine.vm.provision 'shell', path:   cmd, name: cmd, run: "always", privileged: false }
            CMD_SCRIPT_ALWAYS      = -> (cmd) { machine.vm.provision 'shell', path:   cmd, name: cmd, run: "always", privileged: false }

            #authorize default public ssh key
            CMD_INLINE_ROOT.call("mkdir -p /root/.ssh/")
            CMD_INLINE.call     ("mkdir -p /home/vagrant/.ssh/")
            if File.file?("#{Dir.home}/.ssh/id_rsa.pub")
                ssh_pub_key = File.readlines("#{Dir.home}/.ssh/id_rsa.pub").first.strip
                CMD_INLINE_ROOT.call("printf '\\n%s\\n' '#{ssh_pub_key}' >> /root/.ssh/authorized_keys")
                CMD_INLINE.call     ("printf '\\n%s\\n' '#{ssh_pub_key}' >> /home/vagrant/.ssh/authorized_keys")
            end

            #copy private ssh key
            if File.file?("#{Dir.home}/.ssh/id_rsa")
                machine.vm.provision "file",  source: "~/.ssh/id_rsa", destination: "/home/vagrant/.ssh/id_rsa"
                CMD_INLINE.call("chown vagrant:vagrant /home/vagrant/.ssh/id_rsa")
                CMD_INLINE.call("chmod 600 /home/vagrant/.ssh/id_rsa")
            else
                if File.file?("ansible-local/ansible-local.pub")
                    ssh_pub_key = File.readlines("ansible-local/ansible-local.pub").first.strip
                    CMD_INLINE_ROOT.call("printf '\\n%s\\n' '#{ssh_pub_key}' >> /root/.ssh/authorized_keys")
                    CMD_INLINE.call     ("printf '\\n%s\\n' '#{ssh_pub_key}' >> /home/vagrant/.ssh/authorized_keys")
                    machine.vm.provision "file",  source: "ansible-local/ansible-local.priv", destination: "/home/vagrant/.ssh/id_rsa"
                    CMD_INLINE.call     ("chown vagrant:vagrant /home/vagrant/.ssh/id_rsa")
                    CMD_INLINE.call     ("chmod 600 /home/vagrant/.ssh/id_rsa")
                end
            end

            #copy gitconfig
            if File.file?("#{Dir.home}/.gitconfig")
                machine.vm.provision "file",  source: "~/.gitconfig", destination: "/home/vagrant/.gitconfig"
            end

            #entrevista preconditions
            CMD_INLINE.call("cp /vagrant/linux-interview* ~")
            CMD_INLINE.call("cp /vagrant/{README.txt,q2.in}  ~")
            CMD_INLINE.call("chmod +x ~/linux-interview.test")

            machine.vm.provision "shell", inline: $admin_preconditions
            machine.vm.provision "shell", inline: $user_preconditions, privileged: false
        end
    end
end
