# vi: set ft=ruby :
VAGRANTFILE_API_VERSION = '2'
Vagrant.require_version '>= 1.8.2'

CURRENT_DIR = File.expand_path(File.dirname(__FILE__))
DIRNAME     = File.basename(CURRENT_DIR)

#host  = RbConfig::CONFIG['host_os']
hosts = {
    #10.10.10.1 is configured as bridged between the host and 10.10.1.x guests
    #"#{DIRNAME}.example.com"  => "10.10.10.10",
    "mongodb-01.example.com" => "10.10.10.11",
    "mongodb-02.example.com" => "10.10.10.12",
    "mongodb-03.example.com" => "10.10.10.13",
}

#vagrant-hosts is a hard requirement
raise "vagrant-hosts plugin must be installed: $ vagrant plugin install vagrant-hosts" unless Vagrant.has_plugin? "vagrant-hosts"

#cross-platform way of finding an executable in the $PATH.
def which(cmd)
    exts = ENV['PATHEXT'] ? ENV['PATHEXT'].split(';') : ['']
    ENV['PATH'].split(File::PATH_SEPARATOR).each do |path|
        exts.each do |ext|
            exe = File.join(path, "#{cmd}#{ext}")
            return exe if File.executable?(exe) && !File.directory?(exe)
        end
    end
    nil
end

host_counter = 0; Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    hosts.each do |name, ip|
        config.vm.define name do |machine|
            #machine.vm.box = "centos/7" #broken on Windows when used as vagrant host
            #workarounds:
            # => use a non official centos image with vbguest additions preinstalled
            # => install rsync on the Windows host
            # => use vagrant-vbguest plugin to install automatically vbguest into the vm
            # => sync manually the required files [currently used]
            machine.vm.box      = "ubuntu/trusty64"
            machine.vm.hostname = name
            machine.vm.network :private_network, ip: ip

            machine.vm.provider "virtualbox" do |vbox|
                vbox.name = name
                vbox.linked_clone = true if Vagrant::VERSION =~ /^1.8/
                vbox.customize ["modifyvm", :id, "--memory", 512]           #MB
                vbox.customize ["modifyvm", :id, "--cpuexecutioncap", "50"] #%
            end

            #$ vagrant plugin install vagrant-hosts
            if Vagrant.has_plugin?('vagrant-hosts')
                machine.vm.provision :hosts, sync_hosts: true
            elsif Vagrant.has_plugin?('vagrant-hostmanager')
                machine.hostmanager.enabled     = true
                machine.hostmanager.manage_host = true
                machine.hostmanager.aliases     = aliases
            end

            #authorize default public ssh key
            machine.vm.provision 'shell', inline: "mkdir -p /root/.ssh/"
            machine.vm.provision 'shell', inline: "mkdir -p /home/vagrant/.ssh/", privileged: false
            if File.file?("#{Dir.home}/.ssh/id_rsa.pub")
                ssh_pub_key = File.readlines("#{Dir.home}/.ssh/id_rsa.pub").first.strip
                machine.vm.provision 'shell', inline: "printf '\\n%s\\n' '#{ssh_pub_key}' >> /root/.ssh/authorized_keys"
                machine.vm.provision 'shell', inline: "printf '\\n%s\\n' '#{ssh_pub_key}' >> /home/vagrant/.ssh/authorized_keys", privileged: false
            end

            #echo cmds, lambda syntax: http://stackoverflow.com/questions/8476627/what-do-you-call-the-operator-in-ruby
            CMD_SCRIPT_ROOT        = -> (cmd) { machine.vm.provision 'shell', path:   cmd, name: cmd, privileged: true  }
            CMD_SCRIPT             = -> (cmd) { machine.vm.provision 'shell', path:   cmd, name: cmd, privileged: false }
            CMD_INLINE_ROOT        = -> (cmd) { machine.vm.provision 'shell', inline: cmd, name: cmd, privileged: true  }
            CMD_INLINE             = -> (cmd) { machine.vm.provision 'shell', inline: cmd, name: cmd, privileged: false }
            CMD_SCRIPT_ALWAYS_ROOT = -> (cmd) { machine.vm.provision 'shell', path:   cmd, name: cmd, run: "always", privileged: false }
            CMD_SCRIPT_ALWAYS      = -> (cmd) { machine.vm.provision 'shell', path:   cmd, name: cmd, run: "always", privileged: false }

            #authorize default public ssh key
            CMD_INLINE_ROOT.call("mkdir -p /root/.ssh/")
            CMD_INLINE.call     ("mkdir -p /home/vagrant/.ssh/")
            if File.file?("#{Dir.home}/.ssh/id_rsa.pub")
                ssh_pub_key = File.readlines("#{Dir.home}/.ssh/id_rsa.pub").first.strip
                CMD_INLINE_ROOT.call("printf '\\n%s\\n' '#{ssh_pub_key}' >> /root/.ssh/authorized_keys")
                CMD_INLINE.call     ("printf '\\n%s\\n' '#{ssh_pub_key}' >> /home/vagrant/.ssh/authorized_keys")
            end

            #copy private ssh key
            if File.file?("#{Dir.home}/.ssh/id_rsa")
                machine.vm.provision "file",  source: "~/.ssh/id_rsa", destination: "/home/vagrant/.ssh/id_rsa"
                CMD_INLINE.call("chown vagrant:vagrant /home/vagrant/.ssh/id_rsa")
                CMD_INLINE.call("chmod 600 /home/vagrant/.ssh/id_rsa")
            else
                if File.file?("ansible-local/ansible-local.pub")
                    ssh_pub_key = File.readlines("ansible-local/ansible-local.pub").first.strip
                    CMD_INLINE_ROOT.call("printf '\\n%s\\n' '#{ssh_pub_key}' >> /root/.ssh/authorized_keys")
                    CMD_INLINE.call     ("printf '\\n%s\\n' '#{ssh_pub_key}' >> /home/vagrant/.ssh/authorized_keys")
                    machine.vm.provision "file",  source: "ansible-local/ansible-local.priv", destination: "/home/vagrant/.ssh/id_rsa"
                    CMD_INLINE.call     ("chown vagrant:vagrant /home/vagrant/.ssh/id_rsa")
                    CMD_INLINE.call     ("chmod 600 /home/vagrant/.ssh/id_rsa")
                end
            end

            #copy gitconfig
            if File.file?("#{Dir.home}/.gitconfig")
                machine.vm.provision "file",  source: "~/.gitconfig", destination: "/home/vagrant/.gitconfig"
            end

            #only execute ansible when all hosts are ready
            host_counter = host_counter + 1
            if host_counter == hosts.length
                if which('ansible-playbook')
                    machine.vm.provision "ansible" do |ansible|
                        ansible.verbose  = "vvv"
                        ansible.playbook = "ansible.yml"
                        #ansible.galaxy_role_file = "requirements.yml"
                    end
                else
                    machine.vm.provision "ansible_local" do |ansible|
                        ansible.verbose        = "vvv"
                        ansible.playbook       = "ansible.yml"
                        ansible.inventory_path = "development.hosts"
                        ansible.limit          = "all"
                        #ansible.sudo           = true
                        #ansible.raw_arguments  = [
                             #"--connection=paramiko",
                            #"--private-key=/vagrant/.vagrant/machines/.../private_key"
                        #]
                        #ansible.galaxy_role_file = "requirements.yml"
                    end
                end
            end

        end
    end
end
